### ISSUE TITLE
no matches for kind "StatefulSet"

### ISSUE THREAD

**Issue by TNissen377** [piraeusdatastore/piraeus#12]
I m unable to apply 
kubectl apply -f https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml

I get the following errors:
```
unable to recognize "https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"
unable to recognize "https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

I have changed the StatefulSet to apps/v1 (not knowing if thats the right way but it resolves it), but for the 2nd one i couldnt find a solution.

I m using Ubuntu 18.04 /rancher / kubectl

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by TNissen377** [comment]
So I upgraded kubectl (client & server) to 1.17 and changed the following:

`diff --git a/deploy/all.yaml b/deploy/all.yaml
index 1b4ee09..e7f26f9 100644
--- a/deploy/all.yaml
+++ b/deploy/all.yaml
@@ -424,7 +424,7 @@ spec:
       - operator: Exists
         effect: NoSchedule
 ---
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: piraeus-csi-controller
@@ -725,7 +725,7 @@ roleRef:
   name: csi-cluster-driver-registrar-role
   apiGroup: rbac.authorization.k8s.io
 ---
-apiVersion: extensions/v1beta1
+apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   name: piraeus-csi-node
@@ -736,6 +736,10 @@ spec:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 1
+  selector:
+    matchLabels:
+      app.kubernetes.io/name: piraeus
+      app.kubernetes.io/component: piraeus-csi-node
   template:
     metadata:
       labels:
`
Now i could deploy the pods. After giving a lot more cpu to my cluster - tons of ressources are needed :) , the "piraeus-node" still doesnt come up.

I get the following error:
`

  | Exec lifecycle hook ([/init/cmd/poststart-node.sh]) for  Container "node" in Pod  "piraeus-node-z2v5s_kube-system(13351a58-7976-4326-8f50-569ded3c7cde)"  failed - error: command '/init/cmd/poststart-node.sh' exited with 2: +  exec , message: "POSTSTART: piraeus-node-z2v5s  2020-01-17_15-11-55\n'/init/conf/linstor-client.conf' ->  '/etc/linstor/linstor-client.conf'\n'/init/cmd/gojq' ->  '/usr/local/bin/jq'\n+ exec\n"`

So by now i ll go back again to kvaps/kube-linstor, which works well so far. I ll have a look at this project.

**Comment by zlmitche** [comment]
I am running into the same issue. I manually updated the apps/v1beta1 lines to apps/v1 for the DaemonSet and StatefulSet. But have now got this error when applying the all.yaml

> error: error validating "all.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by zlmitche** [comment]
When I use the --validate=false i receive the following error.

> The DaemonSet "piraeus-csi-node" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/component":"piraeus-csi-node", "app.kubernetes.io/name":"piraeus"}: `selector` does not match template `labels`

**Comment by zlmitche** [comment]
Now I've hit the same wall @TNissen377 found. I got all the pods to start excep the piraeus-server which is posting the following error.

> Exec lifecycle hook ([/init/cmd/poststart-node.sh]) for Container "node" in Pod "piraeus-node-5gbbv_kube-system(9591c91e-c358-49f2-abb9-8f3485c52a8d)" failed - error: command '/init/cmd/poststart-node.sh' exited with 2: + exec , message: "POSTSTART: piraeus-node-5gbbv 2020-01-22_16-08-23\n'/init/conf/linstor-client.conf' -> '/etc/linstor/linstor-client.conf'\n'/init/cmd/gojq' -> '/usr/local/bin/jq'\n+ exec\n"

This is after updating the all.yaml to use apps/v1 instead of extensions/v1beta1 in teh DaemonSet and apps/v1beta1 in the StatefulSet. Also adding the following lines to the piraeus-csi-node Daemonset:
>  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-csi-node

**Comment by alexzhc** [comment]
@zlmitche and @TNissen377 ,  sorry for the late reply. 

Currently we've only tested with Kube 1.15 and 1.16. We are on the way to test more kubelet versions and make it compatible.

**Comment by TNissen377** [comment]
It fails also with 1.16 - no difference at all.

**Comment by zlmitche** [comment]
Yes we tried on 16.2 and 16.6 both failed. I've moved on to kvaps.

**Comment by alexzhc** [comment]
ok, I'll test 1.6 again.

**Comment by alexzhc** [comment]
@TNissen377 and @zlmitche, I have tested yaml on kubelet 1.4, 1.5, 16 & 1.7, and made adjustment accordingly. Please try the latest all.yaml, and let me know if any other issue pops up.  A [simple demo](https://github.com/piraeusdatastore/piraeus#using-storage) is also added.  

BTW, please feel free to join the slack channel (link valid for 14 days): https://join.slack.com/t/piraeus-datastore/shared_invite/enQtOTE4MzA4MzY3NTA5LTI0MGZmZDRmMjE3ZWM1YWJiMzFjMjEyMDg2MWRhNDQxNjY2OGE3ODgwMWI3ZGRhN2QyMDBhMDAwZDY2ZmY2ODU

**Comment by TNissen377** [comment]
This issue is solved by the latest update. (Tested with kubelt 1.7). But its components are not tested. So the snapshotter wont work with the old CRDs. These have been updated to beta in Kubernetes 1.17. But i will open another issue for that.
