### ISSUE TITLE
Etcd pods fail to install

### ISSUE THREAD

**Issue by kapolos** [piraeusdatastore/piraeus#15]
Pods can't seem to discover each other so they keep on crashing. Since they're being installed under `kube-system`, perhaps the advertisement should be like `piraeus-etcd-2.kube-system` instead of `piraeus-etcd-2.piraeus-etcd` ?

```
2020-02-09 08:22:09.978560 I | embed: advertise client URLs = http://piraeus-etcd-2.piraeus-etcd:2379
{"level":"warn","ts":1581232959.9791162,"caller":"netutil/netutil.go:121","msg":"failed to resolve URL Host","url":"http://piraeus-etcd-2.piraeus-etcd:2380","host":"piraeus-etcd-2.piraeus-etcd:2380","retry-interval":1,"error":"i/o timeout"}
{"level":"warn","ts":1581232959.9792569,"caller":"netutil/netutil.go:131","msg":"failed to resolve URL Host; returning","url":"http://piraeus-etcd-2.piraeus-etcd:2380","host":"piraeus-etcd-2.piraeus-etcd:2380","retry-interval":1,"error":"i/o timeout"}
2020-02-09 08:22:39.988125 C | etcdmain: failed to resolve http://piraeus-etcd-2.piraeus-etcd:2380 to match --initial-cluster=piraeus-etcd-2=http://piraeus-etcd-2.piraeus-etcd:2380 (failed to resolve "http://piraeus-etcd-2.piraeus-etcd:2380" (i/o timeout))
```

![image](https://user-images.githubusercontent.com/10794126/74098216-46f84800-4b1e-11ea-94bd-169e7f74ea0a.png)

**Comment by kapolos** [comment]
From a quick look, I think the issue lies in this line:

https://github.com/piraeusdatastore/piraeus/blob/08b5bd8e0a04128c28b6ac26a932c3defd57783d/dockerfiles/piraeus-init/config-etcd.sh#L4

**Comment by alexzhc** [comment]
@kapolos the etcd cluster that came with all.yaml is for testing purpose. The etcd nodes discover one another by using kube-dns or core-dns. From the posted error message, it seems dns resolve fails. Please check if kube-dns/core-dns is working in your cluster.  BTW, you can use external etcd cluster by change the etcd:// address in 20_controller.yaml, and only apply 20_controller.yaml, 30_node.yaml and 40_csi.yaml. As for how to set up external etcd cluster, check our child-project: https://github.com/piraeusdatastore/runc-etcd

**Comment by alexzhc** [comment]
BTW, please feel free to join the slack channel (link valid for 14 days): https://join.slack.com/t/piraeus-datastore/shared_invite/enQtOTE4MzA4MzY3NTA5LTI0MGZmZDRmMjE3ZWM1YWJiMzFjMjEyMDg2MWRhNDQxNjY2OGE3ODgwMWI3ZGRhN2QyMDBhMDAwZDY2ZmY2ODU

**Comment by kapolos** [comment]
@alexzhc You are right! I just checked the event logs and dns is indeed having issues. Sorry for the trouble.
