### ISSUE TITLE
drbd-module-loader - drbd9-noble:v9.2.10: make not found

### ISSUE THREAD

**Issue by BokuNoGF** [piraeusdatastore/piraeus#189]
Hello!

Upon installing v2.5.2 of piraeus-operator on Ubuntu 24.04, the drbd-module-loader for satellite nodes is failing to run with the following error:

```
/entry.sh: line 152: make: command not found
```

Seems like the image doesn't have `make` installed, maybe due to the base ubuntu image not including it anymore?

Looking at the drbd Dockerfile, seems like they install `make` explicitly: https://github.com/LINBIT/drbd/blob/b1c9d2d793c9e24ea3673b69ad3957073eb01141/docker/Dockerfile.noble#L11

**Comment by WanzenBug** [comment]
You are right. It is even listed in the other ubuntu variants, not sure why it did not make it into the Ubuntu 24.04 version. Updated images should be [available soon](https://github.com/piraeusdatastore/piraeus/actions/runs/10035836058/job/27732497298).
