### ISSUE TITLE
piraeus-controller goes into NotReady constantly

### ISSUE THREAD

**Issue by alemonmk** [piraeusdatastore/piraeus#21]
`readinessProbe` settings are too tight that it went into NotReady then Ready loop constantly.

The default `timeoutSeconds` of 1s (probably injected by kubelet) caused so many of "Timeout exceeded while awaiting headers" since I noticed it took a while to respond to `linstor controller list-properties`.

I increased the `timeoutSeconds` to 5s then it stayed at ready. I think we should define it in the deployment file. I also increased the `periodSeconds` so it does not spam the `rest-access.log`.

By the way, why are we mounting `/etc/localtime`? It caused me headaches because `/etc/localtime` on Fedora CoreOS for some reason is a empty directory. I don't see the reason since other deployments of Linstor does not do this.

**Comment by alexzhc** [comment]
Good catch. Previously, I was trying to get the entire cluster up as fast as possible. So will follow the readinessProbe change. 

Mounting /etc/localtime is meant to set the pod timezone to that of the host.  I have noticed it not working on some hosts. Let me try some other methods for this.

**Comment by alexzhc** [comment]
changes have been made accordingly.
1. relent readinessProbe to 5 sec
2. change timezone to /usr/share/zoneinfo/Etc/UTC format

**Comment by alexzhc** [comment]
changes have been made accordingly.

relent readinessProbe to 5 sec
change timezone to /usr/share/zoneinfo/Etc/UTC format

**Comment by alemonmk** [comment]
Hey, I looked into your commit, actually the culprit is `timeoutSeconds` not `periodSeconds` (though it's probably better to change it as well), I think 3 seconds is enough, 5 would be a safer bet. Also only controller need to be changed, other things are perfectly fine with old settings.
