### ISSUE TITLE
DRBD_IMG_TAG: v9.0.21 does not exists for Ubuntu

### ISSUE THREAD

**Issue by bratao** [piraeusdatastore/piraeus#26]
Hi,
After freaking out because I could not get piraeus to work, I found out that it was trying to install a version of DRBD that do not exists.

In deploy/all.yaml it set DRBD_IMG_TAG: v9.0.21

And in init-node.sh it try to get the version or install:
```
elif [[ "v$( modinfo drbd \| awk '/^version: / {print $2}' )" == "${DRBD_IMG_TAG}-1" ]]; then
--
```
But https://launchpad.net/~linbit/+archive/ubuntu/linbit-drbd9-stack only contains the v9.0.22

**Comment by alexzhc** [comment]
bruno, please do not "freak out" before reading the code carefully. 

You get the code wrong here. It has nothing to do with PPA. Instead, it is trying to do`docker run --rm -v /lib/modules:/lib/modules -v 
 /usr/src:/usr/src:ro quay.io/piraeusdatastore/drbd9-bionic:v9.0.21` by `curl docker.sock`

v9.0.21 image is right there in https://quay.io/repository/piraeusdatastore/drbd9-bionic

**Comment by alexzhc** [comment]
Please get a 4-worker-node k8s cluster running with kube-dns/core-dns setup, then come to slack and ping me.
