### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by madetara** [piraeusdatastore/piraeus#27]
Hello

I'm not quite sure whether it's me doing something wrong, or README is outdated, but it says to label desired nodes with `piraeus/enabled=true`, while [spec](https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml) uses `piraeus/node=true` as selector

Thanks in advance

**Comment by alexzhc** [comment]
Thanks for point it out. I will correct it.

**Comment by alexzhc** [comment]
corrected, thanks
