### ISSUE TITLE
Prestop-etcd is creating empty dumps

### ISSUE THREAD

**Issue by bratao** [piraeusdatastore/piraeus#36]
Hello, 
on dockerfiles/piraeus-init/bin/prestop-etcd.sh you do a dump of keys using:
```
etcdctl get --prefix "LINSTOR/" -w simple > "${data_dir}_${mod_time}/keys.txt"
etcdctl get --prefix "LINSTOR/" -w json > "${data_dir}_${mod_time}/keys.json"
```

This creates a empty dump for me. In my database the prefix is "/LINSTOR/"

**Comment by alexzhc** [comment]
Linstor 1.4.2 uses `LINSTOR/` prefix. It has been changed to `/LINSTOR/` in later linstor versions. I have updated `quay.io/repository/piraeusdatastore/piraeus-init:v0.5.7` with `etcdctl get --prefix ""` for "dumping everything"

**WARNING: Please read the updated README and do not update etcds unless you absolutely have to.** See issue https://github.com/piraeusdatastore/piraeus/issues/32
