### ISSUE TITLE
/etc/drbd.conf is a directory

### ISSUE THREAD

**Issue by nickadam** [piraeusdatastore/piraeus#37]
`kubectl apply -f https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml` resulted in /etc/drbd.conf being a directory and pod/piraeus-node-* failing.

I was able to fix this by running `touch /etc/drbd.conf` on all nodes before launching.

**Comment by rck** [comment]
deployment via these yaml files is hopefully EoL soon. Please try to use the operator instead: https://github.com/piraeusdatastore/piraeus-operator
