### ISSUE TITLE
[Question] Does Piraeus now support k8s v1.18.x?

### ISSUE THREAD

**Issue by guofengzh** [piraeusdatastore/piraeus#38]
README lists that priaeus support k8s until v1.17.x.

When will Piraues support v1.18.x?

**Comment by lys791227** [comment]
support v1.18.0  ok！

**Comment by guofengzh** [comment]
Great, Thanks.

I close it

**Comment by lys791227** [comment]
大侠，我问一下，我选"layerlist: drbd storage" 的sotrageClass&nbsp; 总是penging
请大侠指导一下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "piraeusdatastore/piraeus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 中午12:29
收件人:&nbsp;"piraeusdatastore/piraeus"<piraeus@noreply.github.com&gt;;
抄送:&nbsp;"LYSLYS"<1836290661@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [piraeusdatastore/piraeus] [Question] Does Piraeus now support k8s v1.18.x? (#38)





 
Great, Thanks.
 
I close it
