### ISSUE TITLE
Latest release on quay.io

### ISSUE THREAD

**Issue by bratao** [piraeusdatastore/piraeus#44]
Hello,
I´m waiting for a new release on quay.io, but the latest version is still 1.7.1
https://quay.io/repository/piraeusdatastore/piraeus-server?tab=history

Is there still a supported location for installation?

**Comment by rck** [comment]
It is. Quite frankly we forgot, maybe we can improve with some automation. There will be linstor-server-1.8.0 very soon (next days, max early next week), so I guess I skip the 1.7.x releases and then jump to 1.8.0

**Comment by bratao** [comment]
😍

**Comment by WanzenBug** [comment]
piraeus-server 1.8.0 is now available on quay.io
updated piraeus-client will follow soon
