### ISSUE TITLE
Piraeus supports for arm64

### ISSUE THREAD

**Issue by huchengze** [piraeusdatastore/piraeus#71]
I have tested various functions of piraeus on x86 machines, and I am very excited about its high availability and high performance, but it seems that piraeus only supports x86 now.

I have successfully completed the arm64 images of all projects written by golang, but I cannot make the arm64 versions of the following two images:
quay.io/piraeusdatastore/piraeus-server
quay.io/piraeusdatastore/drbd9

If you have a plan for piraeus to support arm64, I will do my best to help.

**Comment by rck** [comment]
the `drbd9-*` kernel module loaders should be easy to build, they don't have any dependency on any architecture specific code. They are mainly a distribution, some dependencies, a tarball and shell script. As long as the base distributions (Focal, CentOS7/8,...) are available, this should be `docker build`-able as of now.

The piraeus-server should be easy as well, but it fetches some components from the public LINBIT repos. Should be easy as well, as the main parts here are not arch specific as well (some Python, some Java), but we (as LINBIT) would have to expose our arm repos to make it build out of the box. That is some internal discussion I have to have if we want to do that, or if this is x86 only and only available LINBIT customers. I will start this discussions, if you don't get a response within a week, feel free to ask again.

**Comment by Philipp-Reisner** [comment]
@huchengze all parts of Piraeus-DS are tested on multiple architectures (x86_64, arm64, ppc64el, s390x, mips64el) and known to work. LINBIT, one of the Piraeus-DS' contributors, maintains a multi-arch container registry, that also carries containers for arm64. This registry is part of LINBIT's SDS product. Maybe this is an option for you.
Currently, there is no contributor on the project that works on arm64 container images for the public Piraeus-DS repositories.

**Comment by huchengze** [comment]
@Philipp-Reisner I'm sorry to reply so late, thanks for your help.

Do you mean I can get the images from drbd.io and do I need to register an account?
Is there an easier way to get the diferent archs of image drbd.io/drbd9-bionic?

**Comment by rck** [comment]
- drbd.io registry is for LINBIT customers only, so you would have to be a customer. You can contact `sales@linbit.com` or get in touch on the web page if that is an option for you. But again, customers only.
- the images we have on drbd.io are multi-arch. so if you pull something like `drbd.io/drbd9-rhel8` on a `amd64` machine your get the amd64 one, if you pull on a `s390x` you get one for that. and so on.
