### ISSUE TITLE
Build multi-arch images

### ISSUE THREAD

**Issue by Jukie** [piraeusdatastore/piraeus#74]
Would like to use images that support multiple architectures for mixed clusters or at least additional images per architecture.

I'd like to contribute this but would need to understand the CI system for this repo.

More info here - https://docs.docker.com/engine/reference/commandline/manifest/

**Comment by Jukie** [comment]
I found it under workflows, can use https://github.com/piraeusdatastore/piraeus/commit/c694efc1306b3886d2272d55aff1fd2535670f89 as a guide and submit a PR later.

**Comment by WanzenBug** [comment]
Hi!

Thanks for taking the initiative. Don't hesitate to ask here if you have any questions. 

One problem you'll likely encounter is that we currently use the Linstor and DRBD packages distributed by LINBIT, which are only free to download on x86_64

**Comment by rck** [comment]
also see https://github.com/piraeusdatastore/piraeus/issues/71

**Comment by Jukie** [comment]
Ah damn, so I guess this isn't even possible then right?

**Comment by Jukie** [comment]
Unless you mean only the pre-built packages are an issue. Is the source code still available somewhere? I could alternatively use multi-stage builds.

**Comment by rck** [comment]
after some internal discussion we decided that we want to open up Piraeus for multiple architectures. Which one would be the one you would want to work on? Then we can add the packages for that to the public repos and then you/we can work on the rest

**Comment by Jukie** [comment]
Do you mean the architecture or docker image?
If the former it'd be nice to add support for all the "typical" architectures used in other public repos. 
[K8s dashboard](https://hub.docker.com/layers/kubernetesui/dashboard/v2.2.0/images/sha256-c15240ed4f2563273caf3445a594afaf9eeca99ac5b139bca25ef682e6c9ab16?context=explore) for example supports `amd64`, `arm`, `arm64`, `ppc64le`, and `s390x`. I personally would only have a use for the first three but could validate all.
If the latter, I can start with the piraeus-client but initially planned on adding a PR for all anyways.

**Comment by rck** [comment]
I meant the architecture(s). I'd say we open them up gradually, starting with `arm64`, as I'd assume this is the one most people are interested in. If we have that one, adding new ones is trivial.

After we put the packages in the repos I'd assume the PR is small and easy enough to review, so perfectly fine it is then just one PR. Speaking of the packages we need to put in place: For `$reasons` this has to wait till Monday. I will ping you as soon as they are there. The only challenging container will be `drbd-driver-loader`, as we need one container per supported distribution and I'm not sure if all the base images exist for all architectures. But that is fine as well, the `drbd-driver-loader` is not strictly necessary and having only a subset of distributions it can be used with on non-amd64 is fine as well.

**Comment by Jukie** [comment]
Sounds reasonable, thanks for the update!

**Comment by rck** [comment]
@Jukie We now have the packages in place. I did successful arm64 test builds for `piraeus-{server,client}` on one of my arm64 boxes. Guess you can now start adding this architecture.

**Comment by Jukie** [comment]
Awesome, thanks for the update!

**Comment by Jukie** [comment]
@rck please take a look at https://github.com/piraeusdatastore/piraeus/pull/76

**Comment by toelke** [comment]
I added #84 to keep this going forward.

**Comment by WanzenBug** [comment]
Currently we have:
* [x] piraeus-client #84 
* [ ] piraeus-server
* [ ] drbd9-* loader
* [ ] drbd-reactor
* [ ] piraeus-init (does anybody use that anymore? I don't think so @alexzhc?)

**Comment by toelke** [comment]
I am currently looking at `piraeus-operator` -- that's the next image that fails on my cluster. Is that a reasonable next step?

**Comment by WanzenBug** [comment]
See above: I think that are all the core images required for piraeus.

**Comment by WanzenBug** [comment]
@toelke I think that's it :partying_face: 

Thank you _so_ much for your efforts!

**Comment by toelke** [comment]
Sure thing.
My cluster (hybrid amd64+arm64 is running).

**Comment by WanzenBug** [comment]
I think we forgot to close this issue. piraeus-init isn't used anymore. So all done.
